# Generated by Django 3.2 on 2022-08-20 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_patient_doctor_field'),
        ('checklist', '0004_remove_checklist_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklisttemplate'),
        ),
    ]
